# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: SAP HANA HA deploy
  hosts: 127.0.0.1
  connection: local
  roles:
  - role: forminator
    vars:
      sap_tf_project_path: './tf'
      sap_state: '{{ state | default("present") }}'
      sap_hana_backint_install: '{{ sap_hana_backint_bucket_name | default("") != "" }}'
      sap_hana_backint_bucket_name: '{{ sap_hana_backint_bucket_name | default("") }}'
      fqdn_name: '{{ sap_host_fqdn }}'
      sap_tf_variables:
        project_id: '{{ sap_project_id }}'
        subnetwork: '{{ sap_subnetwork }}'
        subnetwork_project: '{{ sap_subnetwork_project_id | default("") }}'
        source_image_name: '{{ sap_source_image_name }}'
        source_image_project: '{{ sap_source_image_project }}'

        sap_hana_primary_zone: '{{ sap_hana_primary_zone }}'
        sap_hana_primary_instance_name: '{{ sap_hana_primary_instance_name }}'
        sap_hana_primary_instance_ip: '{{ sap_hana_primary_instance_ip }}'
        sap_hana_primary_instance_type: '{{ sap_hana_primary_instance_type | default("n1-highmem-32") }}'
        sap_hana_primary_use_public_ip: '{{ sap_hana_primary_use_public_ip }}'
        sap_hana_primary_boot_disk_size: '{{ sap_hana_primary_boot_disk_size | default(30) }}'
        sap_hana_primary_boot_disk_type: '{{ sap_hana_primary_boot_disk_type | default("pd-balanced") }}'
        sap_hana_primary_autodelete_boot_disk: '{{ sap_hana_primary_autodelete_boot_disk | default(true) }}'
        sap_hana_primary_data_disk_size: '{{ sap_hana_primary_data_disk_size }}'
        sap_hana_primary_log_disk_size: '{{ sap_hana_primary_log_disk_size }}'
        sap_hana_primary_shared_disk_size: '{{ sap_hana_primary_shared_disk_size }}'
        sap_hana_primary_usrsap_disk_size: '{{ sap_hana_primary_usrsap_disk_size }}'
        sap_hana_primary_swap_disk_size: '{{ sap_hana_primary_swap_disk_size }}'
        sap_hana_primary_data_disk_type: '{{ sap_hana_primary_data_disk_type }}'
        sap_hana_primary_log_disk_type: '{{ sap_hana_primary_log_disk_type }}'
        sap_hana_primary_shared_disk_type: '{{ sap_hana_primary_shared_disk_type }}'
        sap_hana_primary_usrsap_disk_type: '{{ sap_hana_primary_usrsap_disk_type }}'
        sap_hana_primary_swap_disk_type: '{{ sap_hana_primary_swap_disk_type }}'
        sap_hana_primary_addon_disks: '{{ sap_hana_primary_addon_disks }}'
        sap_hana_primary_service_account_email: '{{ sap_hana_primary_service_account_email | default("{}@{}.iam.gserviceaccount.com".format(sap_hana_primary_service_account_email | default("sap-common-sa"), sap_project_id)) }}'
        sap_hana_primary_network_tags: '{{ sap_hana_primary_network_tags | default([sap_hana_primary_network_tags | default("sap-allow-all")]) }}'
        sap_hana_primary_pd_kms_key: '{{ sap_hana_primary_pd_kms_key | default(None) }}'
        sap_hana_primary_labels: '{{ sap_hana_primary_labels }}'
        sap_hana_primary_instance_group_name: '{{ sap_hana_primary_instance_group_name }}'
        sap_hana_primary_named_ports: '{{ sap_hana_primary_named_ports }}'

        sap_hana_secondary_zone: '{{ sap_hana_secondary_zone }}'
        sap_hana_secondary_instance_name: '{{ sap_hana_secondary_instance_name }}'
        sap_hana_secondary_instance_ip: '{{ sap_hana_secondary_instance_ip }}'
        sap_hana_secondary_instance_type: '{{ sap_hana_secondary_instance_type | default("n1-highmem-32") }}'
        sap_hana_secondary_use_public_ip: '{{ sap_hana_secondary_use_public_ip }}'
        sap_hana_secondary_boot_disk_size: '{{ sap_hana_secondary_boot_disk_size | default(30) }}'
        sap_hana_secondary_boot_disk_type: '{{ sap_hana_secondary_boot_disk_type | default("pd-balanced") }}'
        sap_hana_secondary_autodelete_boot_disk: '{{ sap_hana_secondary_autodelete_boot_disk | default(true) }}'
        sap_hana_secondary_data_disk_size: '{{ sap_hana_secondary_data_disk_size }}'
        sap_hana_secondary_log_disk_size: '{{ sap_hana_secondary_log_disk_size }}'
        sap_hana_secondary_shared_disk_size: '{{ sap_hana_secondary_shared_disk_size }}'
        sap_hana_secondary_usrsap_disk_size: '{{ sap_hana_secondary_usrsap_disk_size }}'
        sap_hana_secondary_swap_disk_size: '{{ sap_hana_secondary_swap_disk_size }}'
        sap_hana_secondary_data_disk_type: '{{ sap_hana_secondary_data_disk_type }}'
        sap_hana_secondary_log_disk_type: '{{ sap_hana_secondary_log_disk_type }}'
        sap_hana_secondary_shared_disk_type: '{{ sap_hana_secondary_shared_disk_type }}'
        sap_hana_secondary_usrsap_disk_type: '{{ sap_hana_secondary_usrsap_disk_type }}'
        sap_hana_secondary_swap_disk_type: '{{ sap_hana_secondary_swap_disk_type }}'
        sap_hana_secondary_addon_disks: '{{ sap_hana_secondary_addon_disks }}'
        sap_hana_secondary_service_account_email: '{{ sap_hana_secondary_service_account_email | default("{}@{}.iam.gserviceaccount.com".format(sap_hana_secondary_service_account_email | default("sap-common-sa"), sap_project_id)) }}'
        sap_hana_secondary_network_tags: '{{ sap_hana_secondary_network_tags | default([sap_hana_secondary_network_tags | default("sap-allow-all")]) }}'
        sap_hana_secondary_pd_kms_key: '{{ sap_hana_secondary_pd_kms_key | default(None) }}'
        sap_hana_secondary_labels: '{{ sap_hana_secondary_labels }}'
        sap_hana_secondary_instance_group_name: '{{ sap_hana_secondary_instance_group_name }}'
        sap_hana_secondary_named_ports: '{{ sap_hana_secondary_named_ports }}'

        network_project: '{{ sap_network_project_id }}'
        sap_hana_ilb_name: '{{ sap_hana_ilb_name }}'
        sap_hana_health_check_port: '{{ sap_hana_health_check_port }}'
        sap_hana_health_check_port_name: '{{ sap_hana_health_check_port_name }}'
        sap_hana_ilb_ip_address: '{{ sap_hana_ilb_ip_address }}'
        sap_hana_health_check_name: '{{ sap_hana_health_check_name }}'
        sap_hana_backend_service_name: '{{ sap_hana_backend_service_name }}'
        
  # - role: gcp-secrets-manager
  tags: [hana, assertions]

- name: SAP HANA configure
  hosts: hana
  become: yes
  roles:
  - role: sap-hana-ha
    vars:
      sap_hana_backint_bucket_name: '{{ sap_hana_backint_bucket_name | default("") }}'
      sap_hana_primary_instance_name: '{{ sap_hana_primary_instance_name }}'
      sap_hana_secondary_instance_name: '{{ sap_hana_secondary_instance_name }}'
      sap_hana_primary_instance_ip: '{{ sap_hana_primary_instance_ip }}'
      sap_hana_secondary_instance_ip: '{{ sap_hana_secondary_instance_ip }}'
      sap_hana_vip: '{{ sap_hana_ilb_ip_address }}'
      hana_health_check_port: '{{ sap_hana_health_check_port }}'
      sap_hana_primary_data_disk_size: '{{ sap_hana_primary_data_disk_size }}'
      sap_hana_primary_log_disk_size: '{{ sap_hana_primary_log_disk_size }}'
      sap_hana_primary_shared_disk_size: '{{ sap_hana_primary_shared_disk_size }}'
      sap_hana_primary_usrsap_disk_size: '{{ sap_hana_primary_usrsap_disk_size }}'
      sap_hana_primary_swap_disk_size: '{{ sap_hana_primary_swap_disk_size }}'
      sap_hana_secondary_data_disk_size: '{{ sap_hana_secondary_data_disk_size }}'
      sap_hana_secondary_log_disk_size: '{{ sap_hana_secondary_log_disk_size }}'
      sap_hana_secondary_shared_disk_size: '{{ sap_hana_secondary_shared_disk_size }}'
      sap_hana_secondary_usrsap_disk_size: '{{ sap_hana_secondary_usrsap_disk_size }}'
      sap_hana_secondary_swap_disk_size: '{{ sap_hana_secondary_swap_disk_size }}'
      sap_host_fqdn: '{{ sap_host_fqdn }}'
  tags: [hana]

- name: Run assertions on HANA
  hosts: hana
  become: yes
  tasks:
  - include_role:
      name: sap-hana-ha
      tasks_from: assertions
    vars:
      sap_hana_primary_instance_name: '{{ sap_hana_primary_instance_name }}'
      sap_hana_secondary_instance_name: '{{ sap_hana_secondary_instance_name }}'
  tags: [hana, assertions]