# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Create the mount point directory
  file:
    path: "{{ sap_sapmnt_mount }}"
    state: directory
    mode: '0755'
  become: yes

- name: Mount NFS share to mount sapmnt directory
  mount: 
    path: "{{ sap_sapmnt_mount }}"
    src: "{{ sapmnt_nfs_server_path }}"
    fstype: nfs
    opts: vers=3,defaults
    state: mounted
  become: yes

- name: Ensure NFS mount is persistent across reboots
  lineinfile:
    path: /etc/fstab
    regexp: '^{{ sapmnt_nfs_server_path }} {{ sap_sapmnt_mount }} nfs'
    line: "{{ sapmnt_nfs_server_path }} {{ sap_sapmnt_mount }} nfs vers=3,defaults,nofail 0 0"
    create: yes
  become: yes