# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Include base role
  include_role:
    name: base

- name: Modify localhost entry in line in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "::1 localhost"
    insertafter: '^127\.0\.0\.1'
    state: present

- name: include hosts-file role
  include_role:
    name: hosts-file
  vars:
    hosts_file_entries: {}
    hosts_file_peers: '{{ ansible_play_hosts }}'

- name: update /etc/hosts file with fqdn entries for replacing
  replace:
    path: /etc/hosts
    regexp: "{{ item.old }}"
    replace: "{{ item.new }}"
  loop:
    - { old: "{{ sap_hana_zone }}.c.{{ sap_project_id }}.internal", new: "{{ sap_host_fqdn }}" }

- name: Include storage role
  include_role:
    name: storage
  vars:
    disks: "{{ sap_hana_disks }}"
    logvols: "{{ sap_hana_logvols }}"

- name: update /etc/idmapd.conf file NetappVolume entry settings
  replace:
    path: /etc/idmapd.conf
    regexp: "localdomain"
    replace: "defaultv4iddomain.com"

- name: restart nfsidmap service
  command: nfsidmap -c

- name: include sapmnt nfs role
  include_role:
    name: sapmnt-nfs-scaleout

- name: ensure pre-requisite folders has right permissions
  file:
    path: "{{ item }}"
    mode: 0755
    state: directory
  with_items:
    - '{{ sap_hana_log_mountpoint }}/{{ sap_hana_sid }}'
    - '{{sap_hana_data_mountpoint}}/{{ sap_hana_sid }}'

- name: Include hana packages download role
  include_role:
    name: sap-hana-download-packages
  when: sap_hana_is_master | bool

- name: Include sap preconfigure agent role
  include_role:
    name: sap-preconfigure
  when:
  - ansible_os_family == "RedHat"
  - ansible_distribution_major_version | int < 8
  - sap_hana_is_master | bool

- name: Include sap hana preconfigure agent role
  include_role:
    name: sap-hana-preconfigure
  when:
  - ansible_os_family == "RedHat"
  - sap_hana_is_master | bool

- name: Include sap hana install role
  include_role:
    name: sap-hana-install
  when: sap_hana_is_master | bool

- name: Include sap ssh keygen role
  include_role:
    name: ssh-keygen
  when: sap_hana_is_master | bool

- name: Include sap parameters set role
  include_role:
    name: sap-hana-set-parameters
  when: sap_hana_is_master | bool

- name: Include sap hana start role
  include_role:
    name: sap-hana-start
  when: sap_hana_is_master | bool

- name: Include sap host agent role
  include_role:
    name: sap-hostagent

- name: Include copy ssh keys role
  include_role:
    name: sap-hana-copy-ssh-keys
  when: sap_hana_is_worker | bool

- name: Ensure "sapsys" and "{{ sap_hanashm_user }}" group and "{{ sap_hana_user }}" user is created
  block:
    - name: Ensure group "sapsys" exists with correct gid
      group:
        name: "{{ item.group }}"
        state: present
        gid: "{{ item.gid }}"
      with_items:
        - { group: sapsys, gid: "{{ sap_sapsys_gid }}" }
        - { group: "{{ sap_hanashm_user }}", gid: "{{ sap_shm_gid }}" }
    - name: Ensure "{{ sap_hana_user }}" user exists
      user:
        name: "{{ sap_hana_user }}"
        uid: "{{ sap_hana_system_uid }}"
        group: sapsys
        groups: "{{ sap_hanashm_user }}"
        state: present
  when: sap_hana_is_worker | bool

- name: Include sap hana worker node add role
  include_role:
    name: sap-hana-add-worker-nodes
  when: sap_hana_is_master | bool

- name: Include sap hana stop role
  include_role:
    name: sap-hana-stop
  when: sap_hana_is_master | bool

- name: Include sap hana start role
  include_role:
    name: sap-hana-start
  when: sap_hana_is_master | bool

- name: Include SAP hana backint role
  include_role:
    name: sap-hana-backint
  when:
  - sap_hana_is_master | bool
  - sap_hana_backint_install | bool

- name: Include SAP HANA Fast Restart Role
  include_role:
    name: sap-hana-fast-restart-scaleout
  when: 
  - sap_hana_fast_restart|bool == true

- name: include ops-agent role
  include_role:
    name: gcp-ops-agent-install
  vars:
    agent_type: ops-agent
  when: ansible_os_family == "Suse"

- name: include gcloud sdk update
  include_role:
    name: gcp-gcloud-update
  when: ansible_os_family == "Suse"

- name: include gcp misc installations
  include_role:
    name: gcp-misc-adjustments

- name: Include sap hana stop role
  include_role:
    name: sap-hana-stop