# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Include base role
  include_role:
    name: base

- name: Cluster packages upgrade - specific changes for SLES15SP4
  command: zypper in -t patch -y SUSE-SLE-Product-HA-15-SP4-2022-3507=1
  when: 
  - ansible_os_family == 'Suse'
  - ansible_distribution_version == '15.4'

- name: Modify localhost entry in line in /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "::1 localhost"
    insertafter: '^127\.0\.0\.1'
    state: present

- name: Include storage role
  include_role:
    name: storage
  vars:
    disks: "{{ sap_hana_disks }}"
    logvols: "{{ sap_hana_logvols }}"

- name: Include sap hana pre-configure role
  include_role:
    name: sap-hana-preconfigure
  when:
  - ansible_os_family == "RedHat"
  - ansible_distribution_major_version == '8'

- name: Create hanabackup directory in /hana/shared
  file:
    path: /hana/shared/hanabackup
    state: directory
    mode: "0755"

- name: Include hana packages download role
  include_role:
    name: sap-hana-download-packages

- name: wait for zypper process to release locks 
  shell: |
      sleep 60; while true; do unset result; result=$(find /var/log -mmin -1 -name zypper.log); if [[ -z "$result" ]]; then break; fi; sleep 30; done;
  args:
     executable: /bin/bash
  when: ansible_os_family == 'Suse'

- name: updating the crmsh cluster package
  command: zypper up -y crmsh
  when: |
    ansible_os_family == 'Suse'
  ignore_errors: true

- name: updating the fence agent package
  command: zypper up -y fence-agents
  when: |
    ansible_os_family == 'Suse'
  ignore_errors: true

- name: include hosts-file role
  include_role:
    name: hosts-file
  vars:
    hosts_file_entries: {}
    hosts_file_peers: '{{ ansible_play_hosts }}'

- name: Modify hosts-file to include the virtualhost name - primary
  replace:
    path: /etc/hosts
    regexp: "{{ item.old }}"
    replace: "{{ item.new }}"
  loop:
    - { old: "{{ sap_hana_primary_zone}}.c.{{ sap_project_id }}.internal", new: "{{ sap_host_fqdn }}" }
    - { old: "{{ sap_hana_secondary_zone}}.c.{{ sap_project_id }}.internal", new: "{{ sap_host_fqdn }}" }
    
- name: ensure /hana has right permissions
  file:
    path: /hana
    mode: 0755
    state: directory

- name: Install Packages
  shell: |
    yum -y install compat-sap-c++-11
    yum -y install resource-agents-sap-hana
  when: ansible_os_family == 'RedHat'

- name: Include sap hana install role
  include_role:
    name: sap-hana-install

- name: Include sap hana start role
  include_role:
    name: sap-hana-start

- name: Include SAP hostagent install role
  include_role:
    name: sap-hostagent

- name: Include sap hana ssfs copy keys role
  include_role:
    name: sap-hana-ssfs-keys

- name: Include sap hana backup config role
  include_role:
    name: sap-hana-config-backup

- name: Include sap hana hdb user create role
  include_role:
    name: sap-hana-hdb-user

- name: Include sap hana hdb userstore role
  include_role:
    name: sap-hana-hdb-userstore
  vars:
    hdb_us_become_user: '{{ sap_hana_user }}'
    hdb_us_db_host: localhost
    hdb_us_db_password: '{{ sap_hana_db_system_password }}'
    hdb_us_db_port: '3{{ sap_hana_instance_number }}15'
    hdb_us_db_user: '{{ sap_hana_monitoring_user }}'
    hdb_us_key: '{{ sap_hana_user_store_key }}'
    hdb_us_source_file: '/usr/sap/{{ sap_hana_sid }}/home/.sapenv.sh'

- name: Include sap hana backup role
  include_role:
    name: sap-hana-backup

- name: wait for zypper process to release locks 
  shell: |
      sleep 60; while true; do unset result; result=$(find /var/log -mmin -1 -name zypper.log); if [[ -z "$result" ]]; then break; fi; sleep 30; done;
  args:
     executable: /bin/bash
  when: ansible_os_family == 'Suse'

- name: upgrading the latest SAPHanaSR package
  command: zypper in -y SAPHanaSR-0.162.3
  when: |
    ansible_os_family == 'Suse'
  ignore_errors: true

- name: Include sap hana hsr config role
  include_role:
    name: sap-hana-hsr

- name: Include pacemaker install/config role
  include_role:
    name: pacemaker-hana
  vars:
    sap_cluster_user_password: '{{ sap_hana_cluster_user_password }}'

- name: Wait for cluster to be stable
  wait_for:
    timeout: 180

- name: Include SAP hana backint role
  include_role:
    name: sap-hana-backint
  when: sap_hana_backint_install|bool == true

- name: Include SAP HANA Fast Restart Role
  include_role:
    name: sap-hana-fast-restart
  when: sap_hana_fast_restart|bool == true

- name: Regularize the cluster
  shell: |
    pcs resource move rsc_vip_int-primary
    sleep 120
    pcs resource clear rsc_vip_int-primary
    sleep 60
    pcs resource cleanup SAPHana_{{ sap_hana_sid }}_HDB{{ sap_hana_instance_number }}
  when: not (sap_hana_is_primary | bool) and ansible_os_family == "RedHat"

- name: cleanup stopped and failed crm resources
  shell: |
    crm resource cleanup
  when: ansible_os_family == "Suse"

- name: Wait for cluster to be stable
  wait_for:
    timeout: 180

- name: include sap hana initial backup of sysdb and tenantdb
  include_role:
    name: sap-schedule-hana-backup
  vars:
    hdb_us_become_user: '{{ sap_hana_user }}'
    hdb_us_db_host: '{{ sap_hana_primary_instance_name }}'
    hdb_us_db_password: '{{ sap_hana_db_system_password }}'
    hdb_us_db_port: '3{{ sap_hana_instance_number }}13'
    hdb_us_db_user: backupadm 
    hdb_us_source_file: '/usr/sap/{{ sap_hana_sid }}/home/.sapenv.sh'
  when: (sap_hana_backint_install|bool == true) and (sap_hana_is_primary | bool)

- name: include sap-hana-monitoring role
  include_role:
    name: gcp-sap-agent
  when: ansible_os_family == "Suse"

- name: include gcloud sdk update
  include_role:
    name: gcp-gcloud-update
  when: ansible_os_family == "Suse"

- name: Modify hosts-file to include the virtualhost name - primary
  replace:
    path: /etc/hosts
    regexp: "{{ item.old }}"
    replace: "{{ item.new }}"
  loop:
    - { old: "{{ sap_hana_primary_zone}}.c.{{ sap_project_id }}.internal", new: "{{ sap_host_fqdn }}" }
    - { old: "{{ sap_hana_secondary_zone}}.c.{{ sap_project_id }}.internal", new: "{{ sap_host_fqdn }}" }
    
- name: include gcp misc installations
  include_role:
    name: gcp-misc-adjustments
