# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: create exports file for nfs share from primary server 
  copy:
    dest: '{{ file_path }}' 
    content: '{{ file_content }}' 
  when: sap_target_machine_ip != '' 

- name: execute exportsfs command 
  command: exportfs -ra
  when: sap_target_machine_ip != '' 

- name: restart the nfs-server service 
  systemd:
    name: nfs-server 
    enabled: true
    state: restarted
  when: sap_target_machine_ip != '' 
