# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Webdispatcher-Standalone deploy
  hosts: 127.0.0.1
  connection: local
  roles:
  - role: forminator
    vars:
      sap_tf_project_path: './tf'
      sap_state: '{{ state | default("present") }}'
      fqdn_name: '{{ sap_host_fqdn }}'
      sap_zone: '{{ sap_nw_zone }}'
      sap_tf_variables:
        project_id: '{{ sap_project_id }}'
        subnetwork: '{{ sap_subnetwork }}'
        subnetwork_project: '{{ sap_subnetwork_project_id | default("") }}'
        source_image_name: '{{ sap_source_image_name}}'
        source_image_project: '{{ sap_source_image_project }}'
        sap_nw_zone: '{{ sap_nw_zone }}'
        sap_nw_instance_name: '{{ sap_nw_instance_name }}'
        sap_nw_instance_ip: '{{ sap_nw_instance_ip }}'
        sap_nw_instance_type: '{{ sap_nw_instance_type | default("n2d-standard-8") }}'
        sap_nw_boot_disk_size: '{{ sap_nw_boot_disk_size | default(30) }}'
        sap_nw_boot_disk_type: '{{ sap_nw_boot_disk_type | default("pd-balanced") }}'
        sap_nw_autodelete_boot_disk: '{{ sap_nw_autodelete_boot_disk | default(true) }}'
        sap_nw_usrsap_disk_size: '{{ sap_nw_usrsap_disk_size | default(20) }}'
        sap_nw_usrsap_disk_type: '{{ sap_nw_usrsap_disk_type | default("pd-balanced") }}'
        sap_nw_create_instance_group: '{{ sap_nw_create_instance_group | default(true) }}'
        sap_nw_instance_group_name: '{{ sap_nw_instance_group_name }}'
        sap_nw_service_account_email: '{{ sap_nw_service_account_email | default("{}@{}.iam.gserviceaccount.com".format(sap_nw_service_account_name | default("sap-common-sa"), sap_project_id)) }}'
        sap_nw_network_tags: '{{ sap_nw_network_tags | default(["sap-allow-all"]) }}'
        sap_nw_pd_kms_key: '{{ sap_nw_pd_kms_key }}'
        sap_nw_labels: '{{ sap_nw_labels }}'
#  - role: gcp-secrets-manager 
  tags: [nw]

- name: SAP Webdispatcher-Standalone configure
  hosts: nw
  become: yes
  roles:
  - role: webdisp-standalone
  tags: [nw]
